CuaHangBanRau/Models/SanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangBanRau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public int SoLuong { get; set; }
        public int GiaBan { get; set; }
        public string HinhAnh { get; set; }
        public string MoTa { get; set; }
        public int MaHang { get; set; }
        public int MaLoai { get; set; }
    }
}

CuaHangBanRau/Controllers/HinhAnhsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CuaHangBanRau.Models;

namespace CuaHangBanRau.Controllers
{
    public class HinhAnhsController : Controller
    {
        private CuaHangRauEntities1 db = new CuaHangRauEntities1();

        // GET: HinhAnhs
        public ActionResult Index(int MaSP)
        {
            return View(db.HinhAnhs.Where(x => x.MaSP == MaSP).ToList());
        }

        // GET: HinhAnhs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HinhAnh hinhAnh = db.HinhAnhs.Find(id);
            if (hinhAnh == null)
            {
                return HttpNotFound();
            }
            return View(hinhAnh);
        }

        // GET: HinhAnhs/Create
        public ActionResult Create()
        {
            ViewBag.SanPham = new SelectList(db.SanPhams, "MaSP", "TenSP");
            return View();
        }

        // POST: HinhAnhs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaHinhAnh,HinhAnh1,MaSP")] HinhAnh hinhAnh)
        {

            ViewBag.SanPham = new SelectList(db.SanPhams, "MaSP", "TenSP");
            if (ModelState.IsValid)
            {
                db.HinhAnhs.Add(hinhAnh);
                db.SaveChanges();
                return RedirectToAction("Index", new { MaSP = hinhAnh.MaSP });
            }

            return View(hinhAnh);
        }

        // GET: HinhAnhs/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.SanPham = new SelectList(db.SanPhams, "MaSP", "TenSP");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HinhAnh hinhAnh = db.HinhAnhs.Find(id);
            if (hinhAnh == null)
            {
                return HttpNotFound();
            }
            return View(hinhAnh);
        }

        // POST: HinhAnhs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaHinhAnh,HinhAnh1,MaSP")] HinhAnh hinhAnh)
        {
            ViewBag.SanPham = new SelectList(db.SanPhams, "MaSP", "TenSP");
            if (ModelState.IsValid)
            {
                db.Entry(hinhAnh).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { MaSP = hinhAnh.MaSP });
            }
            return View(hinhAnh);
        }

        // GET: HinhAnhs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HinhAnh hinhAnh = db.HinhAnhs.Find(id);
            if (hinhAnh == null)
            {
                return HttpNotFound();
            }
            return View(hinhAnh);
        }

        // POST: HinhAnhs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HinhAnh hinhAnh = db.HinhAnhs.Find(id);
            db.HinhAnhs.Remove(hinhAnh);
            db.SaveChanges();
            return RedirectToAction("Index", new { MaSP = hinhAnh.MaSP });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CuaHangBanRau/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CuaHangBanRau.BUS;
using CuaHangBanRau.Models;

namespace CuaHangBanRau.Controllers
{
    public class SanPhamsController : Controller
    {
        private SanPhamAPI api = new SanPhamAPI();
        private HangAPI hangAPI = new HangAPI();
       

        // GET: SanPhams
        public ActionResult Index()
        {
            return View(api.GetSanPhamsResults());
        }

        // GET: SanPhams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GetSanPhamID_Result sanPham = api.GetSanPhamsResult(id.Value);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: SanPhams/Create
        public ActionResult Create()
        {
            ViewBag.Hang = new SelectList(hangAPI.GetHangs(), "MaHang", "TenHang");
         
            return View();
        }

        // POST: SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSP,TenSP,SoLuong,GiaBan,HinhAnh,MoTa,MaHang,MaLoai")] SanPham sanPham)
        {
            ViewBag.Hang = new SelectList(hangAPI.GetHangs(), "MaHang", "TenHang");
          
            if (ModelState.IsValid)
            {
                api.AddSanPham(sanPham);
                return RedirectToAction("Index");
            }

            return View(sanPham);
        }

        // GET: SanPhams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.Hang = new SelectList(hangAPI.GetHangs(), "MaHang", "TenHang");
           
            SanPham sanPham = api.GetSanPham(id.Value);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSP,TenSP,SoLuong,GiaBan,HinhAnh,MoTa,MaHang,MaLoai")] SanPham sanPham)
        {
            ViewBag.Hang = new SelectList(hangAPI.GetHangs(), "MaHang", "TenHang");
         
            if (ModelState.IsValid)
            {
                api.UpdateSanPham(sanPham);
                return RedirectToAction("Index");
            }
            return View(sanPham);
        }

        // GET: SanPhams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = api.GetSanPham(id.Value);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            api.DeleteSanPham(id);
            return RedirectToAction("Index");
        }

        
    }
}

CuaHangBanRau/Controllers/api/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using CuaHangBanRau.Models;

namespace CuaHangBanRau.Controllers.api
{
    public class SanPhamsController : ApiController
    {
        private CuaHangRauEntities1 db = new CuaHangRauEntities1();


        [Route("api/SanPhams/GetSanPhams")]
        public IEnumerable<GetSanPhams_Result> GetSanPhams()
        {
            return db.GetSanPhams().ToList();
        }
      
        [Route("api/SanPhams/GetSanPhamsHang")]
        public IEnumerable<GetSanPhamTheoHang_Result> GetSPTheoHang(int MaHang)
        {
            return db.GetSanPhamTheoHang(MaHang).ToList();
        }

        [Route("api/SanPhams/GetSanPhamResult")]
        public IHttpActionResult GetSanPhamResult(int id)
        {
            GetSanPhamID_Result sanPham = db.GetSanPhamID(id).FirstOrDefault();
            if (sanPham == null)
            {
                return NotFound();
            }

            return Ok(sanPham);
        }
        [Route("api/SanPhams/GetSanPham")]
        public IHttpActionResult GetSanPham(int id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return NotFound();
            }

            return Ok(sanPham);
        }
        [Route("api/SanPhams/PutSanPham")]
        public IHttpActionResult PutSanPham(SanPham sanPham)
        {

            db.Entry(sanPham).State = EntityState.Modified;
            return Ok(db.SaveChanges());

        }
        [Route("api/SanPhams/PostSanPham")]
        // POST: api/SanPhams
        [ResponseType(typeof(SanPham))]
        public IHttpActionResult PostSanPham(SanPham sanPham)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.SanPhams.Add(sanPham);
            return Ok(db.SaveChanges());


        }

        [Route("api/SanPhams/DeleteSanPham")]
        [ResponseType(typeof(SanPham))]
        public IHttpActionResult DeleteSanPham(int id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return NotFound();
            }

            db.SanPhams.Remove(sanPham);
            return Ok(db.SaveChanges());


        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool SanPhamExists(int id)
        {
            return db.SanPhams.Count(e => e.MaSP == id) > 0;
        }
    }
}

CuaHangBanRau/Views/SanPhams/Create.cshtml
@model CuaHangBanRau.Models.SanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HinhAnh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MaHang,ViewBag.Hang as SelectList,new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.MaHang, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CuaHangBanRau/Views/SanPhams/Delete.cshtml
@model CuaHangBanRau.Models.SanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaHang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaLoai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CuaHangBanRau/Views/SanPhams/Details.cshtml
@model CuaHangBanRau.Models.GetSanPhamID_Result

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            <img src="@Model.HinhAnh" height="150"/>
           
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenHang)
        </dd>

       

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaSP }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CuaHangBanRau/Views/SanPhams/Edit.cshtml
@model CuaHangBanRau.Models.SanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>SanPham</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MaSP)

    <div class="form-group">
        @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HinhAnh, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HinhAnh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaHang, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.MaHang, ViewBag.Hang as SelectList, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaHang, "", new { @class = "text-danger" })
        </div>
    </div>

    

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CuaHangBanRau/Views/SanPhams/Index.cshtml
@model IEnumerable<CuaHangBanRau.Models.GetSanPhams_Result>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sản phẩm</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MaSP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TenSP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoLuong)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GiaBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MoTa)
        </th>
        <th>
            Loại
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <th>
                @Html.DisplayFor(modelItem => item.MaSP)
            </th>
            <td>
                @Html.DisplayFor(modelItem => item.TenSP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLuong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaBan)
            </td>
            <td>
                <img src="@item.HinhAnh" height="150" />

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MoTa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenHang)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.MaSP }, new
           {
               @class = "btn btn-primary"
           })
                <a href="@Url.Action("Index", "HinhAnhs", new {MaSP = item.MaSP})" class="btn btn-success">Hình ảnh</a>
            
                @Html.ActionLink("Delete", "Delete", new { id = item.MaSP }, new
           {
               @class = "btn btn-danger"
           })
            </td>
        </tr>
    }

</table>